blueprint:
  name: Simple Climate Control Automation
  description: Start AC with selected mode and temperature when sensor drops below threshold, stop when target temperature is reached
  domain: automation
  input:
    climate_entity:
      name: Climate Entity
      description: The air conditioner/climate device to control
      selector:
        entity:
          filter:
            - domain: climate
    temperature_sensor:
      name: Temperature Sensor
      description: The temperature sensor to monitor
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: temperature
    min_temperature:
      name: Minimum Temperature Threshold
      description: When temperature drops below this, start heating
      default: 20
      selector:
        number:
          min: 5
          max: 35
          step: 0.5
          unit_of_measurement: "°"
          mode: box
    target_temperature:
      name: Target Temperature
      description: Heat to this temperature, then stop
      default: 22
      selector:
        number:
          min: 10
          max: 40
          step: 0.5
          unit_of_measurement: "°"
          mode: box
    ac_temperature:
      name: AC Set Temperature
      description: The temperature to set on the AC when it turns on
      default: 24
      selector:
        number:
          min: 10
          max: 40
          step: 0.5
          unit_of_measurement: "°"
          mode: box
    ac_mode:
      name: AC Mode
      description: The HVAC mode to use when turning on the AC
      default: heat
      selector:
        select:
          options:
            - label: Heat
              value: heat
            - label: Cool
              value: cool
            - label: Heat/Cool (Auto)
              value: heat_cool
            - label: Dry
              value: dry
            - label: Fan Only
              value: fan_only

trigger:
  - platform: numeric_state
    entity_id: !input temperature_sensor
    below: !input min_temperature
    id: "temp_low"
  - platform: numeric_state
    entity_id: !input temperature_sensor
    above: !input target_temperature
    id: "temp_high"
  - platform: homeassistant
    event: start
    id: "ha_start"
  - platform: event
    event_type: automation_reloaded
    id: "automation_reloaded"

action:
  - choose:
      # Temperature dropped below minimum - start AC
      - conditions:
          - condition: trigger
            id: "temp_low"
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input climate_entity
            data:
              temperature: !input ac_temperature
              hvac_mode: !input ac_mode

      # Temperature reached target - stop heating
      - conditions:
          - condition: trigger
            id: "temp_high"
        sequence:
          - service: climate.turn_off
            target:
              entity_id: !input climate_entity

      # On HA start or automation reload - check current state
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: "ha_start"
              - condition: trigger
                id: "automation_reloaded"
        sequence:
          - choose:
              # If temperature is below minimum, start AC
              - conditions:
                  - condition: numeric_state
                    entity_id: !input temperature_sensor
                    below: !input min_temperature
                sequence:
                  - service: climate.set_temperature
                    target:
                      entity_id: !input climate_entity
                    data:
                      temperature: !input ac_temperature
                      hvac_mode: !input ac_mode
              # If temperature is above target, stop heating
              - conditions:
                  - condition: numeric_state
                    entity_id: !input temperature_sensor
                    above: !input target_temperature
                sequence:
                  - service: climate.turn_off
                    target:
                      entity_id: !input climate_entity

mode: single
